@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Christian\AppData\Local\trunk\tools\trufflehog\3.91.1-7b6117a35b5e0572257eae6bb2f24e46;C:\Users\Christian\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Christian\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
